# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization
resources:
- ../../application

namespace: production
commonLabels:
  environment: production

configMapGenerator:
  - name: backend-config
    behavior: merge
    envs:
      - environment
      
patches:
- ingressPatch.yaml
- prodConfigPatch.yaml
- resourcesPatch.yaml
- replicasPatch.yaml
- hpaPatch.yaml
