name: Deploy to Kubernetes cluster

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install node dependencies
        run: npm ci
      - name: Install doctl (to be able to login on Digital Ocean)
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Login to Digital Ocean docker registry
        run: doctl registry login
      - name: Build the docker image
        id: docker_build
        run: docker build . -q -t registry.digitalocean.com/wallfair/backend_k8s:${GITHUB_SHA::6}
      - name: Publish the docker image to Digital Ocean
        run: docker push registry.digitalocean.com/wallfair/backend_k8s:${GITHUB_SHA::6}
  
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Edit deployment image
        uses: stefanprodan/kube-tools@v1
        with:
          kustomize: 4.2.0
          command: |
            cd infra/environments/staging
            kustomize edit set image registry.digitalocean.com/wallfair/backend_k8s:${GITHUB_SHA::6}
            kustomize build .
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.K8S_CONFIG_TEST }}
        with:
          args: apply -k infra/environments/staging
  
