name: Publish new version of the app (Will override version with same tag)

on:
  workflow_dispatch:
    inputs:
      stage:
      version:
        description: 'Tag Version of this deploy'
        required: true
        default: '1.x.x'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install node dependencies
        run: npm ci
      - name: Install doctl (to be able to login on Digital Ocean)
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Login to Digital Ocean docker registry
        run: doctl registry login
      - name: Build the docker image
        run: docker build . -t registry.digitalocean.com/wallfair/backend:${{ github.event.inputs.version }}
      - name: Publish the docker image to Digital Ocean
        run: docker push registry.digitalocean.com/wallfair/backend:${{ github.event.inputs.version }}